foreground   #dad4c7
background   #0E110C
cursor       #dad4c7

color0       #0E110C
color8       #98948b
color1       #5C5D51
color9       #5C5D51
color2       #936E41
color10      #936E41
color3       #79892A
color11      #79892A
color4       #8E952D
color12      #8E952D
color5       #AA9B59
color13      #AA9B59
color6       #AEAE9E
color14      #AEAE9E
color7       #dad4c7
color15      #dad4c7
